[package]
name = "pbjson-types"
version = "0.1.1"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
description = "Protobuf well known types with serde serialization support"
edition = "2018"
license = "MIT"
keywords = ["protobuf", "json", "serde"]
categories = ["encoding"]
repository = "https://github.com/influxdata/pbjson"

[dependencies] # In alphabetical order
bytes = "1.0"
chrono = "0.4"
pbjson = { path = "../pbjson", version = "0.1" }
prost = "0.8"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"

[build-dependencies] # In alphabetical order
prost-build = "0.8"
pbjson-build = { path = "../pbjson-build", version = "0.1" }
